### PR TITLE
Updates aws-sdk-go

### PR DESCRIPTION
**Pull request by wata727**
I noticed that the `aws-sdk-go` included in the current dependency is too old to processed with the development of #308.

However, I decided that the impact of this update was very big, so I submit it as a separate pull request.

### CODE REVIEW

**Comment by yinshiua** [comment]
Thanks! We will take a look at this!

**Comment by SoManyHs** [comment]
Hi @wata727! Thanks so much for your contribution :) Quick question -- what commands did you use to regenerate the mocks? We're testing things out on our end and seeing a slightly different diff, so just wanted to double check what your process was. Thanks!

**Comment by SoManyHs** [comment]
Looks good to me!  👍 We can merge as soon as we get internal approval. Thanks for your contribution, @wata727!

**Comment by SoManyHs** [comment]
@wata727 We were able to get internal approval 🎉 If you're okay with contributing this under the Apache 2.0 license, we can merge this. Thanks again!

**Comment by SoManyHs** [comment]
Sorry @wata727, we're running into some inconsistencies again. Would you mind telling us which commands you used to generate the diffs in your two commits? Thank you!

**Comment by wata727** [comment]
@SoManyHs Thanks for your investigation. Unfortunately, I could not update with a simple command, so I'm experimenting with several commands. It may be difficult to reproduce...

If #315 is easier to merge than this pull request, I want you to close this pull request and merge that.

**Comment by SoManyHs** [comment]
#315 has been merged, so closing this request. Thanks for bringing this to our attention @wata727!

**Pull request closed without merging**
