### PR TITLE
Add --cluster flag to avoid race conditions for simultaneous invokations of ecs-cli

### PR DESCRIPTION
**Pull request by markriggins**
Resolves issue https://github.com/aws/amazon-ecs-cli/issues/174
Resolves issue https://github.com/aws/amazon-ecs-cli/issues/177

### CODE REVIEW

**Comment by euforia** [comment]
@markriggins - awesome.  was looking at implementing this myself.

**Comment by yinshiua** [comment]
@markriggins We would like to merge in one of your commit in this PR https://github.com/aws/amazon-ecs-cli/pull/175/commits/f766ee197ea7e6f56d344b691728092dabff0a39 to resolve the config file bug. Do you mind fixing the indentation and submit a separate PR for that commit?

**Comment by markriggins** [comment]
See https://github.com/aws/amazon-ecs-cli/pull/214

**Comment by markriggins** [comment]
any chance for getting the --cluster flag merged too?

**Comment by yinshiua** [comment]
Adding `--cluster` and `--region` to all commands.
Keeping track of this in this PR https://github.com/aws/amazon-ecs-cli/pull/175

**Pull request closed without merging**
