### PR TITLE
Extend README.md - download specific version

### PR DESCRIPTION
**Pull request by nvtkaszpir**
Extend README with info how to download specific version from the S3, because sometimes you do not want to download the `latest` version.

### CODE REVIEW

**Comment by witsoej** [comment]
Edit on this change (revised text below):

+Using the URLs above, replace `latest` with the desired tag, for example `v0.4.1`. After downloading, remember to rename the binary file to "ecs-cli".

**Comment by kaihendry** [comment]
I don't see the point of downloading an out of date binary. Old binaries for example have old hard coded AMIs which can have security or reliability issues. If anything there needs to be a guidelines how to trigger `curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest` when there is a new release!

**Comment by nvtkaszpir** [comment]
@kaihendry we had an issue that latest binary was producing errors and thus was unusable. That's why this commit was added.

**Comment by yinshiua** [comment]
Resolved conflict and pushed. (Commit https://github.com/aws/amazon-ecs-cli/commit/b476ef6ee7b87737d6429b5e98a48cfa4386d614)

**Pull request closed without merging**
