### PR TITLE
Add missing EC2 instance types and sort list

### PR DESCRIPTION
**Pull request by matthew-noken**
There were a number of missing EC2 instance types, so I've added them and sorted the list by type and size.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by matthew-noken** [comment]
By the way, I've built and tested this change (I originally did it to use the newer t3 class instances).

**Comment by matthew-noken** [comment]
Sure, no problem. Where should the new instances go in that case?

**Comment by SoManyHs** [comment]
@matthew-noken Usually we group instances together by type. So all `t2.*` instances go together, and if you want to add `t3.*` ones they'd go after wherever `t2` was. (See #619)

Thanks!

**Comment by SoManyHs** [comment]
Closing due to lack of response in favor of #630.

**Comment by matthew-noken** [comment]
Sorry, I ran out of time!

**Pull request closed without merging**
